### ISSUE TITLE
[Question] GitLab token permissions

### ISSUE THREAD

**Issue by VincentTam** [eduardoboucas/staticman.net#18]
# Description

In the quick start docs, it's written that a GitLab token needs `read_repository` and `write_repository` permissions.  However, in [the original PR](https://github.com/eduardoboucas/staticman/pull/219#issuecomment-417857360), it's stated `read_repository` & `api` instead.

# Screenshot

![my GitLab bot's token's scopes](https://user-images.githubusercontent.com/5748535/108066590-d274b500-705f-11eb-823e-b8ba84df7c08.png)  
screenshot of [my GitLab bot](https://gitlab.com/staticmanlab)'s account showing only `api` and `read_repository` scopes are needed, no need to use `write_repository`.

**Comment by alexwaibel** [comment]
Good catch, I hadn't seen this documented anywhere previously so I just took my best guess. I'll update the docs to use `api` permission instead.
